### ISSUE TITLE
Tools for removing files from an ensemble

### ISSUE THREAD

**Issue by corviday** [pacificclimate/modelmeta#71]
We have a reasonably solid tool for associating files to an ensemble, but we don't have a good way to remove files from an ensemble. When I've had to do it, I've just run SQL queries on the live database, not an experience I relish.

It would be nice if there was a better way to remove files from an ensemble. Something that would probably be easy to do would be the inverse of the `associate_ensemble` script; you'd pass it one or more file names (and optionally variable names) and an ensemble name and those files are removed from the ensemble.

A fancier system might accept a .yaml file that would provide the attributes of the files you'd like added or removed, something like:

```
add: 
  models:
    model_short_name: CanESM2

  timesets:
    time_resolution: monthly
    multi_year_mean: false

remove:
  timesets:
    multi_year_mean: true
```
but that seems even less likely to be a good use of our time.
